routes/web.php
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', 'Dashboard\AdminsController@login_form')->name('login');
Route::post('/admin/login', 'Dashboard\AdminsController@login')->name('admins.login');
Route::get('/logout', 'Dashboard\AdminsController@logout')->name('logout');
Route::get('/profile', 'Dashboard\AdminsController@profileIndex')->name('admins.profile');
Route::post('/update-profile/{id}', 'Dashboard\AdminsController@updateProfile')->name('admins.profile.update');
Route::group(['prefix' => 'admin'], function () {
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::group(['middleware' => ['role:Super Admin|Settings Admin']], function () {
            Route::resource('dashboard', 'Dashboard\StatisticsController')->only('index');
            Route::prefix('cities')->group(function() {
                Route::get('','Dashboard\CityController@index')->name('cities.index');
                Route::get('/create','Dashboard\CityController@create')->name('cities.create');
                Route::post('/store','Dashboard\CityController@store')->name('cities.store');
                Route::get('/edit/{id}','Dashboard\CityController@edit')->name('cities.edit');
                Route::post('/update/{id}','Dashboard\CityController@update')->name('cities.update');
                Route::post('/{id}','Dashboard\CityController@destroy')->name('cities.destroy');
            });

            Route::prefix('neighborhoods')->group(function() {
                Route::get('','Dashboard\NeighborhoodsController@index')->name('neighborhoods.index');
                Route::get('/create','Dashboard\NeighborhoodsController@create')->name('neighborhoods.create');
                Route::post('/store','Dashboard\NeighborhoodsController@store')->name('neighborhoods.store');
                Route::get('/edit/{id}','Dashboard\NeighborhoodsController@edit')->name('neighborhoods.edit');
                Route::post('/update/{id}','Dashboard\NeighborhoodsController@update')->name('neighborhoods.update');
                Route::post('/{id}','Dashboard\NeighborhoodsController@destroy')->name('neighborhoods.destroy');
            });

            Route::prefix('categories')->group(function() {
                Route::get('','Dashboard\CategoryController@index')->name('categories.index');
                Route::get('/create','Dashboard\CategoryController@create')->name('categories.create');
                Route::post('/store','Dashboard\CategoryController@store')->name('categories.store');
                Route::get('/edit/{id}','Dashboard\CategoryController@edit')->name('categories.edit');
                Route::post('/update/{id}','Dashboard\CategoryController@update')->name('categories.update');
                Route::post('/{id}','Dashboard\CategoryController@destroy')->name('categories.destroy');
                Route::post('/status/{id}', 'Dashboard\CategoryController@updateStatus')->name('categories.status');
            });

            Route::prefix('additions')->group(function() {
                Route::get('','Dashboard\AdditionController@index')->name('additions.index');
                Route::get('/create','Dashboard\AdditionController@create')->name('additions.create');
                Route::post('/store','Dashboard\AdditionController@store')->name('additions.store');
                Route::get('/edit/{id}','Dashboard\AdditionController@edit')->name('additions.edit');
                Route::post('/update/{id}','Dashboard\AdditionController@update')->name('additions.update');
                Route::post('/{id}','Dashboard\AdditionController@destroy')->name('additions.destroy');
                Route::post('/status/{id}', 'Dashboard\AdditionController@updateStatus')->name('additions.status');
            });
            Route::prefix('advertisments')->group(function() {
                Route::get('','Dashboard\AdvertismentController@index')->name('advertisments.index');
                Route::get('/create','Dashboard\AdvertismentController@create')->name('advertisments.create');
                Route::post('/store','Dashboard\AdvertismentController@store')->name('advertisments.store');
                Route::get('/edit/{id}','Dashboard\AdvertismentController@edit')->name('advertisments.edit');
                Route::post('/update/{id}','Dashboard\AdvertismentController@update')->name('advertisments.update');
                Route::post('/{id}','Dashboard\AdvertismentController@destroy')->name('advertisments.destroy');
                Route::post('/status/{id}', 'Dashboard\AdvertismentController@updateStatus')->name('advertisments.status');
            });

            Route::prefix('category')->group(function() {
                Route::get('additions','Dashboard\CatAdditionsController@index')->name('category.additions.index');
                Route::get('additions/create','Dashboard\CatAdditionsController@create')->name('category.additions.create');
                Route::post('additions/store','Dashboard\CatAdditionsController@store')->name('category.additions.store');
                Route::get('additions/edit/{id}','Dashboard\CatAdditionsController@edit')->name('category.additions.edit');
                Route::post('additions/update/{id}','Dashboard\CatAdditionsController@update')->name('category.additions.update');
                Route::post('additions/{id}','Dashboard\CatAdditionsController@destroy')->name('category.additions.destroy');
            });

            Route::prefix('contacts')->group(function() {
                Route::get('','Dashboard\ContactsController@index')->name('contacts.index');
                Route::post('/{id}','Dashboard\ContactsController@destroy')->name('contacts.destroy');
            });
            Route::prefix('users')->group(function() {
                Route::get('','Dashboard\UsersController@index')->name('users.index');
                Route::get('/create','Dashboard\UsersController@create')->name('users.create');
                Route::post('/store','Dashboard\UsersController@store')->name('users.store');
                Route::get('/edit/{id}','Dashboard\UsersController@edit')->name('users.edit');
                Route::post('/update/{id}','Dashboard\UsersController@update')->name('users.update');
                Route::post('/{id}','Dashboard\UsersController@destroy')->name('users.destroy');
                Route::get('/export', 'Dashboard\UsersController@export')->name('users.export');
                Route::get('/show/{id}','Dashboard\UsersController@show')->name('users.show');
            });

            Route::prefix('stores')->group(function() {
                Route::get('','Dashboard\StoresController@index')->name('stores.index');
                Route::get('/create','Dashboard\StoresController@create')->name('stores.create');
                Route::post('/store','Dashboard\StoresController@store')->name('stores.store');
                Route::get('/edit/{id}','Dashboard\StoresController@edit')->name('stores.edit');
                Route::post('/update/{id}','Dashboard\StoresController@update')->name('stores.update');
                Route::post('/{id}','Dashboard\StoresController@destroy')->name('stores.destroy');
                Route::get('/export', 'Dashboard\StoresController@export')->name('stores.export');
                Route::post('/status/{id}', 'Dashboard\StoresController@updateStatus')->name('stores.status');
            });

            Route::prefix('products')->group(function() {
                Route::get('','Dashboard\ProductsController@index')->name('products.index');
                Route::get('/create','Dashboard\ProductsController@create')->name('products.create');
                Route::post('/store','Dashboard\ProductsController@store')->name('products.store');
                Route::get('/edit/{id}','Dashboard\ProductsController@edit')->name('products.edit');
                Route::post('/update/{id}','Dashboard\ProductsController@update')->name('products.update');
                Route::post('/{id}','Dashboard\ProductsController@destroy')->name('products.destroy');
                Route::get('show/{id}','Dashboard\ProductsController@show')->name('products.show');
                Route::post('/status/{id}', 'Dashboard\ProductsController@updateStatus')->name('products.status');
            });

            Route::prefix('products')->group(function() {
                Route::get('additions','Dashboard\ProductAdditionsController@index')->name('product.additions.index');
                Route::get('additions/create','Dashboard\ProductAdditionsController@create')->name('product.additions.create');
                Route::post('additions/store','Dashboard\ProductAdditionsController@store')->name('product.additions.store');
                Route::get('additions/edit/{id}','Dashboard\ProductAdditionsController@edit')->name('product.additions.edit');
                Route::post('additions/update/{id}','Dashboard\ProductAdditionsController@update')->name('product.additions.update');
                Route::post('additions/{id}','Dashboard\ProductAdditionsController@destroy')->name('product.additions.destroy');
            });
        });
        Route::group(['middleware' => ['role:Super Admin']], function () {

            Route::prefix('admins')->group(function() {
                Route::get('','Dashboard\AdminsController@index')->name('admins.index');
                Route::get('/create','Dashboard\AdminsController@create')->name('admins.create');
                Route::post('/store','Dashboard\AdminsController@store')->name('admins.store');
                Route::get('/edit/{id}','Dashboard\AdminsController@edit')->name('admins.edit');
                Route::post('/update/{id}','Dashboard\AdminsController@update')->name('admins.update');
                Route::post('/{id}','Dashboard\AdminsController@destroy')->name('admins.destroy');
            });

        });

app/Models/ProductAddition.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductAddition extends Model
{
    protected $fillable = ['value','product_id','addition_id'];
    protected $appends  = ['addition_name_ar','addition_name_en'];

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

    public function addition()
    {
        return $this->belongsTo(Addition::class, 'addition_id', 'id');
    }

    public function getAdditionNameArAttribute()
    {
        return $this->addition->getTranslation('name','ar');
    }

    public function getAdditionNameEnAttribute()
    {
        return $this->addition->getTranslation('name','en');
    }
}

app/Http/Controllers/Dashboard/ProductAdditionsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductAdditionRequest;
use App\Models\Addition;
use App\Models\Product;
use App\Models\ProductAddition;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;

class ProductAdditionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = ProductAddition::orderBy('created_at', 'desc')->get();
        return view('pages.product_additions.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $prods=Product::all();
        $adds=Addition::all();
        return view('pages.product_additions.create', compact('prods','adds'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductAdditionRequest $request)
    {
        $data = $request->validated();
        ProductAddition::create($data);
        Toastr::success('Product addition added successfully!', 'Success', ["positionClass" => "toast-top-right"]);
        return redirect()->route('product.additions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = ProductAddition::findOrFail($id);
        $prods=Product::all();
        $adds=Addition::all();
        return view('pages.product_additions.edit', compact('product','prods','adds'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = ProductAddition::findOrFail($id);
        $product->value=$request->value;
        $product->product_id=$request->product_id;
        $product->addition_id=$request->addition_id;
        $product->save();
        Toastr::success('product additions updated successfully!', 'Success', ["positionClass" => "toast-top-right"]);
        return redirect()->route('product.additions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = ProductAddition::findOrFail($id);
        $product->delete();
        Toastr::success('product additions deleted!', 'Success', ["positionClass" => "toast-top-right"]);
        return redirect()->back();
    }

}

resources/views/pages/product_additions/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Mobile Toggle-->
                    <button class="burger-icon burger-icon-left mr-4 d-inline-block d-lg-none" id="kt_subheader_mobile_toggle">
                        <span></span>
                    </button>
                    <!--end::Mobile Toggle-->
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">New Record</h5>
                        <!--end::Page Title-->
                        <!--begin::Breadcrumb-->
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item text-muted">
                                <a href="{{route('dashboard.index')}}" class="text-muted">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item text-muted">
                                <a href="{{route('product.additions.index')}}" class="text-muted">Products Additions</a>
                            </li>
                            <li class="breadcrumb-item text-muted">
                                <a href="" class="text-muted">Create Product Additions</a>
                            </li>
                        </ul>
                        <!--end::Breadcrumb-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->

            </div>
        </div>
        <!--end::Subheader-->
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Profile Account Information-->
                <div class="d-flex flex-row">

                    <!--begin::Content-->
                    <div class="flex-row-fluid ml-lg-8">
                        <!--begin::Card-->
                        <div class="card card-custom">
                            <!--begin::Header-->
                            <div class="card-header py-3">
                                <div class="card-title align-items-start flex-column">
                                    <h3 class="card-label font-weight-bolder text-dark">create product additions</h3>
                                    <span class="text-muted font-weight-bold font-size-sm mt-1">create new product additions settings</span>
                                </div>

                            </div>
                            <!--end::Header-->
                            <!--begin::Form-->
                            <form class="form" action="{{route('product.additions.store')}}" method="post">
                                @csrf
                                <div class="card-body">
                                    <!--begin::Heading-->

                                    <!--begin::Form Group-->
                                    <div class="form-group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label">value</label>
                                        <div class="col-lg-9 col-xl-6">

                                            <input class="form-control form-control-lg form-control-solid" type="text" placeholder="value" name="value"/>

                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Select product</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <select name="product_id" class="form-control form-control-lg form-control-solid">
                                                @foreach($prods as $prod)
                                                    <option value="{{$prod->id}}">{{$prod->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Select addition</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <select name="addition_id" class="form-control form-control-lg form-control-solid">
                                                @foreach($adds as $add)
                                                    <option value="{{$add->id}}">{{$add->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <button type="submit" class="btn btn-success mr-2">Save Changes</button>

                                </div>
                            </form>
                            <!--end::Form-->
                        </div>
                        <!--end::Card-->
                    </div>
                    <!--end::Content-->
                </div>
                <!--end::Profile Account Information-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
@endsection

resources/views/pages/product_additions/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Mobile Toggle-->
                    <button class="burger-icon burger-icon-left mr-4 d-inline-block d-lg-none" id="kt_subheader_mobile_toggle">
                        <span></span>
                    </button>
                    <!--end::Mobile Toggle-->
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-1 mr-5">Edit Record</h5>
                        <!--end::Page Title-->
                        <!--begin::Breadcrumb-->
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item text-muted">
                                <a href="{{route('dashboard.index')}}" class="text-muted">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item text-muted">
                                <a href="{{route('product.additions.index')}}" class="text-muted">Products Additions</a>
                            </li>
                            <li class="breadcrumb-item text-muted">
                                <a href="" class="text-muted">Edit Product Additions</a>
                            </li>
                        </ul>
                        <!--end::Breadcrumb-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->

            </div>
        </div>
        <!--end::Subheader-->
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Profile Account Information-->
                <div class="d-flex flex-row">

                    <!--begin::Content-->
                    <div class="flex-row-fluid ml-lg-8">
                        <!--begin::Card-->
                        <div class="card card-custom">
                            <!--begin::Header-->
                            <div class="card-header py-3">
                                <div class="card-title align-items-start flex-column">
                                    <h3 class="card-label font-weight-bolder text-dark">edit product additions</h3>
                                    <span class="text-muted font-weight-bold font-size-sm mt-1">edit product additions settings</span>
                                </div>

                            </div>
                            <!--end::Header-->
                            <!--begin::Form-->
                            <form class="form" action="{{route('product.additions.update',$product->id)}}" method="post">
                                @csrf
                                <div class="card-body">
                                    <!--begin::Heading-->

                                    <!--begin::Form Group-->
                                    <div class="form-group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label">value</label>
                                        <div class="col-lg-9 col-xl-6">

                                            <input class="form-control form-control-lg form-control-solid" type="text" placeholder="value" name="value" value="{{$product->value}}"/>

                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Select product</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <select name="product_id" class="form-control form-control-lg form-control-solid">
                                                @foreach($prods as $prod)
                                                    <option {{ $prod->id == $product->product->id ? 'selected' : '' }}  value="{{$prod->id}}">{{$prod->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-xl-3 col-lg-3 col-form-label">Select addition</label>
                                        <div class="col-lg-9 col-xl-9">
                                            <select name="addition_id" class="form-control form-control-lg form-control-solid">
                                                @foreach($adds as $add)
                                                    <option {{ $add->id == $product->addition->id ? 'selected' : '' }} value="{{$add->id}}">{{$add->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <button type="submit" class="btn btn-success mr-2">Save Changes</button>

                                </div>
                            </form>
                            <!--end::Form-->
                        </div>
                        <!--end::Card-->
                    </div>
                    <!--end::Content-->
                </div>
                <!--end::Profile Account Information-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
@endsection